# Site
name: 'Programmer Biasa'
description: 'opini dan log seorang programmer.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
# disqus: 'demowebsite'
email: 'farispriadi@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    faris:
      name:           Faris Priadi
      site:           https://farispriadi.github.io
      avatar:         assets/images/avatar1.png
      bio:            "Seorang programmer biasa saja"
      email:          farispriadi@gmail.com
      twitter:        https://twitter.com/farispriadi

# Timezones
timezone: Asia/Jakarta
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: faris
      avatar: /assets/images/avatar1.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 5



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, Gemfile.lock]